[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
